sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t guoxiny/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true guoxiny/docker-react npm run test